### ISSUE TITLE
Install error~

### ISSUE THREAD

**Issue by einai** [k0retux/fuddly#27]
Hi ~ 

When I install this fuzzer, I got the message below.

Exception in thread db_handler:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/fuddly/framework/database.py", line 174, in _sql_handler
    self._ok = self._is_valid(connection, cursor)
  File "/home/fuddly/framework/database.py", line 153, in _is_valid
    cur.executescript(fmk_db_sql)
OperationalError: near "AS": syntax error

I think "fmk_db.sql" file is okay, But I don't know why this syntax error occured.
Do you have any idea?

**Comment by k0retux** [comment]
Hi,

Can you provide me with:
- fuddly version you are using (or the commit ID)
- OS info
- python version
- sqlite version

**Comment by krzxy** [comment]
Yes!

1. fuddly version 
release-0.26

2. OS info (Centos 7, uname -a info)
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

3. python version
Python 2.7.5

4. sqlite3 version
3.7.17

Thx.

**Comment by k0retux** [comment]
When you say that it is during fuddly installation, do you mean that it is when you run "fuddly_shell.py" for the first time (when it creates the "fuddly_data" directory and the database)?
I was not able to reproduce your error which seems to be related to an incorrect SQL syntax in the file "framework/fmk_db.sql". Maybe your file is corrupted.
Can you try to see what happens when you remove the "fuddly_data" directory in order for fuddly to create it again with the database?

**Comment by krzxy** [comment]
Exactly right. I mean when I run "fuddly_shell.py" for the first time.
I removed that directory, then run the file again but the result is the same. 

This is full error message below after I interrupted using Ctrl+C .

Exception in thread db_handler:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/fuddly/framework/database.py", line 181, in _sql_handler
    cursor.executescript(fmk_db_sql)
OperationalError: near "AS": syntax error

^CTraceback (most recent call last):
  File "fuddly_shell.py", line 29, in <module>
    fmk = FmkPlumbing()
  File "/home/fuddly/framework/plumbing.py", line 259, in __init__
    ok = self.fmkDB.start()
  File "/home/fuddly/framework/database.py", line 293, in start
    self._thread_initialized.wait(0.1)
  File "/usr/lib64/python2.7/threading.py", line 621, in wait
    self.__cond.wait(timeout, balancing)
  File "/usr/lib64/python2.7/threading.py", line 361, in wait
    _sleep(delay)
KeyboardInterrupt

Can you say that the environment that you tested?

thx.

**Comment by k0retux** [comment]
Can you provide me with the sha1 of your "framework/fmk_db.sql"?
By the way, further to your issue, I tested with python 2.7.13 and python 3.5.3 with sqlite 3.16.2, and everything works as expected.

**Comment by k0retux** [comment]
I assume the problem has been fixed on your side, given you didn't answer to my last comment.
Feel free to reopen it if it's not the case.
